- hosts: local
  tasks:
  - name: Install rsync
    apt:
      name: rsync
      state: present
  - import_role:
      name: mdklatt.python3
  - name: get docker-systemctl-replacement
    git:
      repo: https://github.com/gdraheim/docker-systemctl-replacement.git
      dest: /srv/docker-systemctl-replacement
      force: true
  - name: update systemd
    package: name="systemd" state="latest"
  - name: install systemctl.py
    copy: src="/srv/docker-systemctl-replacement/files/docker/systemctl3.py" dest="/usr/bin/systemctl"
  - name: install systemctl.py
    copy: src="/srv/docker-systemctl-replacement/files/docker/systemctl3.py" dest="/bin/systemctl"
  - import_role:
      name: geerlingguy.postgresql
  - import_role:
      name: geerlingguy.nodejs
  - import_role:
      name: confluent.preflight
    tags:
      - pre-install
  - import_role:
      name: confluent.ssl_CA
    tags:
      - pre-install
  - import_role:
      name: confluent.zookeeper
  - import_role:
      name: confluent.schema-registry
  - import_role:
      name: confluent.connect-distributed
  - import_role:
      name: confluent.ksql
  - import_role:
      name: confluent.kafka-rest
  - import_role:
      name: confluent.tools
    tags:
      - post-install
  - name: restart kafka
    command: systemctl restart confluent-kafka
  - name: restart schema registry
    command: systemctl restart confluent-schema-registry
  - name: restart kafka connect
    command: systemctl restart confluent-kafka-connect
  - name: restart kafka rest proxy
    command: systemctl restart confluent-kafka-rest
  - name: restart ksql
    command: systemctl restart confluent-ksql
  - import_role:
      name: landoop.topics-ui
  - import_role:
      name: landoop.connect-ui
  - import_role:
      name: landoop.schema-registry-ui

- hosts: broker
  tasks:
  - import_role:
      name: confluent.kafka-broker
