- hosts: local
  tasks:
  - import_role:
      name: postgresql
  - import_role:
      name: nodejs
  - import_role:
      name: confluent.preflight
    tags:
      - pre-install
  - import_role:
      name: confluent.ssl_CA
    tags:
      - pre-install
  - import_role:
      name: confluent.zookeeper
  - import_role:
      name: confluent.schema-registry
  - import_role:
      name: confluent.connect-distributed
  - import_role:
      name: confluent.ksql
  - import_role:
      name: confluent.kafka-rest
  - import_role:
      name: confluent.tools
    tags:
      - post-install
  - import_role:
      name: landoop.topics-ui
  - import_role:
      name: landoop.connect-ui
  - import_role:
      name: landoop.schema-registry-ui
- hosts: broker
  tasks:
  - import_role:
      name: confluent.kafka-broker
