local:
  vars:
    security_mode: plaintext
  hosts:
    127.0.0.1:
      ansible_connection: local
broker:
  vars:
    security_mode: plaintext
  hosts:
    127.0.0.1:
      ansible_connection: local
      kafka:
        broker:
          id: 1
zookeeper:
  hosts:
    127.0.0.1:
