#[local]
#localhost ansible_connection=local
#[local:vars]
#security_mode=plaintext
#[local:kafka:broker]
#id=1
local:
  vars:
    security_mode: plaintext
  hosts:
    127.0.0.1:
      ansible_connection: local
broker:
  vars:
    security_mode: plaintext
  hosts:
    127.0.0.1:
      ansible_connection: local
      kafka:
        broker:
          id: 1
zookeeper:
  hosts:
    127.0.0.1:
#all:
#  vars:
#    #ansible_connection: ssh
#    #ansible_ssh_user: centos
#    #ansible_become: true
#    security_mode: plaintext
#preflight:
#  hosts:
#    127.0.0.1:
#ssl_CA:
#  hosts:
#    127.0.0.1:
#zookeeper:
#  hosts:
#    127.0.0.1:
#broker:
#  hosts:
#    127.0.0.1:
#      kafka:
#        broker:
#          id: 1
#    #127.0.0.1:
#    #  kafka:
#    #    broker:
#    #      id: 2
#    #127.0.0.1:
#    #  kafka:
#    #    broker:
#    #      id: 3
#schema-registry:
#  hosts:
#    127.0.0.1:
#connect-distributed:
#  hosts:
#    127.0.0.1:
#kafka-rest:
#  hosts:
#    127.0.0.1:
#ksql:
#  hosts:
#    127.0.0.1:
#tools:
#  hosts:
#    127.0.0.1:
#postgresql:
#  hosts:
#    127.0.0.1:
#nodejs:
#  hosts:
#    127.0.0.1:
