schema_registry_listener_port: 8081

schema:
  registry:
    user: cp-schema-registry
    group: confluent
    config_file: /etc/schema-registry/schema-registry.properties
    service_name: confluent-schema-registry
    systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
    config:
      listeners: http://0.0.0.0:{{schema_registry_listener_port}}
      kafkastore.topic: _schemas
      debug: false
      kafkastore.ssl.endpoint.identification.algorithm: ""
      access.control.allow.methods: "GET,POST,PUT,DELETE,OPTIONS"
      access.control.allow.origin: "*"
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
    systemd:
      enabled: yes
      state: started
